[tool.poetry]
name = "sizing-costing-model"
version = "0.1.0"
description = ""
authors = ["Luke Marshall <luke.marshall@suncable.sg>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.2"
matplotlib = "^3.4.3"
pvlib = {git = "https://github.com/yildizba/pvlib-python.git"}
airtable = "^0.4.8"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
