import sqlite3



conn = sqlite3.connect("phill_test.db")
cur = conn.cursor()
cur.execute(""" CREATE TABLE IF NOT EXISTS INPUTS (
                                    NAME TEXT NOT NULL,
                                    INPUT TEXT NOT NULL);""")

cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('DC_total', 11000)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('num_of_zones', 720)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('zone_area', 140000)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('rack_interval_ratio', 0.01)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('temp_model', 'pvsyst')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('export_lim', 4444444.44)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('storage_capacity', 50000000)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('scheduled_price', 0.00015)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('discount_rate', 0.07)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('start_year', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('revenue_year', 2030)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('end_year', 2059)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc1', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc1', 'MAV_5P13B')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc1', '550W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks1', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc2', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc2', 'SAT_84_600W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc2', '600W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks2', 351)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc3', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc3', 'MAV_6g_10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc3', 'MAV_custom_1377')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_rack3', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc4', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc4', 'SAT_84_660W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc4', '650W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks4', 320)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc5', 2025)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc5', 'MAV_6g_12')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc5', 'MAV_custom_1688')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks5', 296)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc6', 2026)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc6', 'MAV_5P13B')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc6', '550W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks6', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc7', 2026)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc7', 'SAT_84_600W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc7', '600W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks7', 351)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc8', 2026)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc8', 'MAV_6g_10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc8', 'MAV_custom_1377')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_rack8', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc9', 2026)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc9', 'SAT_84_660W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc9', '650W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks9', 320)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc10', 2026)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc10', 'MAV_6g_12')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc10', 'MAV_custom_1688')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks10', 296)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc11', 2027)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc11', 'MAV_5P13B')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc11', '550W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks11', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc12', 2027)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc12', 'SAT_84_600W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc12', '600W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks12', 351)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc13', 2027)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc13', 'MAV_6g_10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc13', 'MAV_custom_1377')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_rack13', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc14', 2027)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc14', 'SAT_84_660W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc14', '650W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks14', 320)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc15', 2027)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc15', 'MAV_6g_12')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc15', 'MAV_custom_1688')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks15', 296)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc16', 2028)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc16', 'MAV_5P13B')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc16', '550W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks16', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc17', 2028)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc17', 'SAT_84_600W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc17', '600W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks17', 351)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc18', 2028)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc18', 'MAV_6g_10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc18', 'MAV_custom_1377')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_rack18', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc19', 2028)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc19', 'SAT_84_660W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc19', '650W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks19', 320)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc20', 2028)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc20', 'MAV_6g_12')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc20', 'MAV_custom_1688')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks20', 296)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc21', 2029)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc21', 'MAV_5P13B')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc21', '550W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks21', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc22', 2029)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc22', 'SAT_84_600W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc22', '600W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks22', 351)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc23', 2029)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc23', 'MAV_6g_10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc23', 'MAV_custom_1377')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_rack23', 363)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc24', 2029)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc24', 'SAT_84_660W')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc24', '650W_M10')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks24', 320)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('year_sc25', 2029)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mount_tech_sc25', 'MAV_6g_12')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('mod_tech_sc25', 'MAV_custom_1688')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('set_racks25', 296)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('num_iterations', 20)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('optimize_for', 'Yield')")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('optimize_target', 46.32)")
cur.execute("INSERT INTO INPUTS(NAME, INPUT) VALUES ('projectID', 'phill_test')")
conn.commit()
conn.close()